defaultPodOptions:
  securityContext:
    fsGroup: 65534

service:
  sonarr:
    controller: sonarr
    ports:
      http:
        port: 8989
  radarr:
    controller: radarr
    ports:
      http:
        port: 7878
  overseer:
    controller: overseer
    ports:
      http:
        port: 5055
  bazarr:
    controller: bazarr
    ports:
      http:
        port: 6767
  tautulli:
    controller: tautulli
    ports:
      http:
        port: 8181
  prowlarr:
    controller: prowlarr
    ports:
      http:
        port: 9696
  flaresolverr:
    controller: flaresolverr
    ports:
      http:
        port: 8191
persistence:
  config-sonarr:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      sonarr:
        main:
          - path: /config
  config-radarr:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      radarr:
        main:
          - path: /config
  config-bazarr:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      bazarr:
        main:
          - path: /config
  config-tautulli:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      tautulli:
        main:
          - path: /config
  config-overseer:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
    retain: true
    advancedMounts:
      overseer:
        main:
          - path: /app/config
  config-prowlarr:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      prowlarr:
        main:
          - path: /config
  media:
    enabled: false
    path: /media
ingress:
  sonarr:
    enabled: false
  radarr:
    enabled: false
  bazarr:
    enabled: false
  overseer:
    enabled: false
  prowlarr:
    enabled: false
  flaresolverr:
    enabled: false
  tautulli:
    enabled: false
controllers:
  sonarr:
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.14.2938
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /usr/bin/env
                  - bash
                  - -c
                  - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
                    read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
  radarr:
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 5.22.1.9832
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /usr/bin/env
                  - bash
                  - -c
                  - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                    read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
  overseer:
    containers:
      main:
        image:
          repository: sctx/overseerr
          tag: 1.34.0
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
  bazarr:
    containers:
      main:
        image:
          repository: linuxserver/bazarr
          tag: 1.5.1
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
          PUID: 1000
          PGID: 1000
  tautulli:
    containers:
      main:
        image:
          repository: ghcr.io/tautulli/tautulli
          tag: v2.15.1
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
          PUID: 1000
          PGID: 1000
  flaresolverr:
    containers:
      main:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.3.21
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
          LOG_LEVEL: info
          LOG_HTML: false
          CAPTCHA_SOLVER: none
  prowlarr:
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/prowlarr
          tag: 1.33.2.5002
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /usr/bin/env
                  - bash
                  - -c
                  - curl --fail localhost:9696/api/v1/system/status?apiKey=`IFS=\> && while
                    read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
